spring:
  datasource:
    url: jdbc:postgresql://stg-db:5432/gym_stg
    username: gym_stg
    password: stg_pass

  profiles:
    active: security

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
  rabbitmq:
    addresses: amqp://stg-rabbit.mycompany.com
    username: stguser
    password: stgpass
    publisher-confirm-type: correlated
    publisher-returns: true

logging:
  level:
    com.gymcrm: INFO
    org.springframework: WARN
    org.springframework.amqp.rabbit.core.RabbitAdmin: INFO
    org.springframework.amqp.rabbit.connection: INFO

management:
  endpoints:
    web:
      exposure:
        include: prometheus,health
  endpoint:
    health:
      show-details: never

security:
  jwt:
    user:
      expiration-ms: 3600000
    service:
      expiration-ms: 300000
    secret: ${JWT_SECRET_STG}
  login:
    max-attempts: 3
    block-minutes: 5
  cors:
    allowed-origins: https://stg.example.com
