spring.datasource.url=jdbc:postgresql://localhost:5432/gymdb
spring.datasource.username=gymuser
spring.datasource.password=pass

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true

logging.pattern.console=[%X{transactionId}] %d{HH:mm:ss.SSS} %-5level %logger{36} - %msg%n
logging.level.root=INFO