spring:
  jpa:
    open-in-view: false
  rabbitmq:
    host: localhost
    port: 5672
    username: gymuser
    password: pass
    publisher-confirm-type: correlated
    publisher-returns: true

logging:
  pattern:
    console: "[%X{transactionId}] %d{HH:mm:ss.SSS} %-5level %logger{36} - %msg%n"
    level:
      org.springframework.amqp.rabbit.core.RabbitAdmin: DEBUG
      org.springframework.amqp.rabbit.connection: DEBUG


security:
  jwt:
    user:
      expiration-ms: 3600000
    service:
      expiration-ms: 300000
  login:
    max-attempts: 3
    block-minutes: 5

service-name: "trainer-workload"

queue-name: "trainer-workload"

resilience4j:
  circuitbreaker:
    instances:
      trainer-workload:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3