spring:
  main:
    allow-bean-definition-overriding: true
  profiles:
    group:
      local: local
      dev: dev,security
      stage: stage,security
      prod: prod,security
      security-test: security
  jpa:
    open-in-view: false

logging:
  pattern:
    console: "[%X{transactionId}] %d{HH:mm:ss.SSS} %-5level %logger{36} - %msg%n"

service-name: "trainer-workload"

queue-name: "trainer-workload"

resilience4j:
  circuitbreaker:
    instances:
      trainer-workload:
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 10s
        permittedNumberOfCallsInHalfOpenState: 3