spring.datasource.url=jdbc:postgresql://localhost:5432/gymdb
spring.datasource.username=gymuser
spring.datasource.password=pass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true