spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        jdbc:
          batch_size: 50
        order_inserts: true
        order_updates: true
        generate_statistics: false
  rabbitmq:
    host: rabbit.prod.mycompany.com
    port: 5672
    username: produser
    password: prodpass
    publisher-confirm-type: correlated
    publisher-returns: true

logging:
  level:
    root: INFO
    com.gymcrm: WARN
    org.springframework: WARN
    org.springframework.amqp.rabbit.core.RabbitAdmin: WARN
    org.springframework.amqp.rabbit.connection: WARN

management:
  endpoints:
    web:
      exposure:
        include: health,prometheus
  endpoint:
    health:
      show-details: never

security:
  jwt:
    secret: ${JWT_SECRET_PROD}
  cors:
    allowed-origins: https://www.example.com
