spring.profiles.active=local
spring.jpa.open-in-view=false

logging.pattern.console=[%X{transactionId}] %d{HH:mm:ss.SSS} %-5level %logger{36} - %msg%n

security.jwt.expiration-ms=3600000
security.login.max-attempts=3
security.login.block-minutes=5